### ISSUE TITLE
NOVAC Program crashing on ReEvaluation of pak file

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#103]
The NOVAC program is crashing when I attempt to ReEvaluate this pak file from Ubinas volcano. To reproduce the error, enter the ReEvaluation Dialog, select the attached pak file in the 'Scan File(s)' section. Then, in the Fit Window tab, load the nfw settings file. This should populate the fit settings. Finally, you will need to ensure that the Reference Files are available at the indicated paths. The CrossSections directory is provided in the attached zip file.

[ExampleReEvaluationCrash.zip](https://github.com/NOVACProject/NOVACProgram/files/3428388/ExampleReEvaluationCrash.zip)

**Comment by dnorgaard-usgs** [comment]
Confirmed the crash in 3.1.  Seems it is related to the use of a solar spectrum file.  This appears to be fixed already in 3.2.
