### ISSUE TITLE
Add property to STD files indicating spectra are summed, not averaged

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#126]
The NOVAC software uses *.pak files internally, but users are able to export spectra to the *.STD format. I tested this export feature and found that the *.std files contain the sum of the individual exposures rather than the average (as is the case for *.std files written by MobileDOAS). Similar to our plans for MobileDOAS, I suggest we add a line to all exported *.std files specifying the parameter 'IntegrationMethod' is equal to 'Sum' in this case.

**Comment by dnorgaard-usgs** [comment]
Added to this commit but needs testing: https://github.com/NOVACProject/SpectralEvaluation/pull/4/commits/cb4e398f5dc9530eab4dad1b14d08fd4033f0a14
