### ISSUE TITLE
'Merge Evaluation Logs' feature has been lost from previous version

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#136]
The NOVAC Program version 20111109 had the feature that allowed users to merge evaluation logs. It was in the 'File' menu. Our partners in Indonesia use this feature relatively often, and are wondering why the newer software no longer contains it.

I also noticed that the 'Split/Merge/Modify Pak files' feature appears to have more functionality in the 20111109 version than in the current version of the software. Is there a good reason for this?

![2021-03-22_16-36-20](https://user-images.githubusercontent.com/15023271/112071435-f9297e00-8b2c-11eb-880f-81307478241c.png)

![2021-03-22_16-37-18](https://user-images.githubusercontent.com/15023271/112071438-f9c21480-8b2c-11eb-82b4-7729c96be15d.png)

**Comment by dnorgaard-usgs** [comment]
We began with a 2009 baseline due to some instability in the 2011 version.  This feature from 2011 has been copied into the current version.  Please check it out and let me know if any changes are desired.
