### ISSUE TITLE
Write EvaluationLogs to sftp server?

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#137]
For each scan the NOVACProgram receives and evaluates, the software currently writes the pak file and the txt file containing the retrieved column densities to the sftp server. It also writes the FluxLogs and Geometry logs there. However, the EvaluationLogs are not written to the sftp server. Why not? These are among the most useful files for the observatories. Can we add them to the list of files that are uploaded? Or is there some reason not to do that?

**Comment by dnorgaard-usgs** [comment]
feature will be available in 3.3
