### ISSUE TITLE
Some files still being written to ftp server after update to version 3.2

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#138]
The CVGHM updated their NOVAC software running at Sinabung Pos to version 3.2 a few weeks ago. As part of this update, they switched the data uploads from ftp to sftp, and configured their credentials for sftp access. Sure enough, data from Sinabung are now being received on the sftp server.

However, for some reason, every now and then files are still written to the ftp server. I'm attaching a screenshot from yesterday. It seems that they are mostly the reference files used for the DOAS analysis, but there are also some stray pak files, txt files, FluxLogs etc. Any idea why? I did check and it looks like at least the pak file and txt file were also sent to the sftp server, so they're not missing from there. It's still a bit strange...

![2021-03-22_16-44-46](https://user-images.githubusercontent.com/15023271/112072302-c2546780-8b2e-11eb-959e-132f1bc1ecd2.png)

**Comment by christophkern** [comment]
The above screenshot is from the following directory on the ftp server:
/sinabung/2021.03.21

**Comment by dnorgaard-usgs** [comment]
Suspect that the observatory unintentionally ran the older version.  I don't see this for the other volcanoes currently there, except for galeras on 3/1.
