### ISSUE TITLE
ReEvaluate traverse - fast computer will crash the program

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/NOVACProgram#19]
When running a reevaluation on a fast, modern, computer then the program will crash due to an overflow of spectra to display.

See also https://github.com/NOVACProject/MobileDOAS/issues/13

**Comment by dnorgaard-usgs** [comment]
Carlos seemed to have encountered this problem. He has provided eval logs to try but so far I have not been able to reproduce.  Perhaps depends on computer specs?

**Comment by dnorgaard-usgs** [comment]
The 200ms delay may be insufficient for some data sets.  A better solution would be to identify the underlying problem so that the delay is not necessary.  Or, so far, it seems the longest delay necessary is 1000ms.

**Comment by mattias42** [comment]
I think I solved this by now. My suggestion for fix is in the MemoryIssueInvestigations branch

**Comment by dnorgaard-usgs** [comment]
Mattias found another bug and fixed it, which seemed to help even more.  There's a slight problem with updating the graphics in this case, so a slight delay (20ms) between scans is still there to help.  Will close after confirmation from user testing.

**Comment by dnorgaard-usgs** [comment]
So far I have not been able to get user support for adequate testing.  I will close this for now and reopen if there are further reports of crashes.
