### ISSUE TITLE
Dual-beam wind measurements

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/NOVACProgram#47]
There used to be a feature that automatically sent configuration (cfgonce.txt) to the instrument to make wind measurement.  At one point when the instrument computer changed this feature broke.  The bug in instrument that broke is now fixed but this is still not working, so there may be another bug in the software.  Note: There is a work around place in hardware program to automatically do the measurements periodically. However, this does not work well if the plume is not overhead. Also, the manual mode (through Control->Make WindMeasurement that also sends configonce) supposedly works.  See ManualWindDlg and RealTimeWind.  Code to send configonce.txt appears to be in both classes.  The RealTimeWind version should create and send the file if a plume is detected.  (This may be difficult to test.)

**Comment by dnorgaard-usgs** [comment]
One option for troubleshooting may be to comment out code that required a plume detection for this to occur and then see if the file is created and send to the instrument computer.  There is also a Debug_WindSpeedMeas.txt that may have useful information.

**Comment by mattias42** [comment]
Have made a first look in the code now and have a difficult time pin pointing what it is that goes wrong. Unfortunately does the Debug_WindSpeedMeas.txt nor StatusLogFile not get sent to the server which makes it difficult to read which condition fails. 

However, I have found a clue in that there is a similar issue with the Composition-mode measurements, which are special scans where many spectra are collected in the plume and outside the plume (original idea with this was to be able to do good quality BrO/SO2 measurements). These work in a similar way, where a number of conditions are checked before a special cfgonce.txt file get sent to the scanner. For this mode of measurements is a Debug_CompositionMeas.txt generated and uploaded to the FTP-server which helps with debugging. For these, it is possible to see that the program sometimes says that it is ok to do composition mode measurements, whereby the program should generate a similar cfgonce.txt file and send it to the instrument. However, I cannot find any signs of a composition-mode measurement from the data on the server which indicates that the program fails to send the cfgonce.txt to the device for some reason.

**Comment by mattias42** [comment]
One improvement to this with commit  d11b41b . There was an error in calculating the time passed since the last wind-speed measurement was made. However, if no measurements are made then this doesn't help. 

Implemented writing more debug-information to the Debug_WindSpeedMeas.txt and uploading these to the FTP-server with commit d648062 .

**Comment by dnorgaard-usgs** [comment]
Do we know where the cfgonce.txt is expected to be?  It does appear to be getting sent, but not to the default novac directory.  It is one up in /mnt/flash, along with cfg.txt.

**Comment by mattias42** [comment]
Had a look at the data in the FTP server and there are now some wind speed measurements being made, not many but some. The problem which this ticket describes is thereby solved.
