### ISSUE TITLE
Implement user-defined obervatory name

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/NOVACProgram#5]
In the newer versions of the program then it is possible to enter a new volcano, but not possible to enter a new observatory. (all recently joined observatories use Chalmers....)

**Comment by dnorgaard-usgs** [comment]
We can make this a free-form text field so that user can enter in any value.  This is in Configuration->Scanning Instrument tab->Info tab.

**Comment by dnorgaard-usgs** [comment]
done
