### ISSUE TITLE
New screen fixed view measurements

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/NOVACProgram#53]
* There is a new measurement mode with viewing only in one direction (Scan angle), implement a new view to display these (column values vs time).

* Also show the time series of the column values, possible for several days.

**Comment by dnorgaard-usgs** [comment]
- Add a tab that shows the different view of data that can be used in either mode (normal, or wide FOV).  Wide FOV mode will be configured into the scanner and read measurement at one angle.  So no flux will calculate and probably will show zero in Today's Flux plot.  
- For the plot in the new tab, perhaps make the number of days to display configurable.

**Comment by dnorgaard-usgs** [comment]
Added option to plot only columns in config dialog for scanner:

![image](https://user-images.githubusercontent.com/25251719/54397019-315e7200-4672-11e9-8881-cf37cadc7d47.png)

Which creates a column plot for current day:

![image](https://user-images.githubusercontent.com/25251719/54397027-3b807080-4672-11e9-8c7c-b5bc1525d582.png)
