### ISSUE TITLE
Add Support for SFTP

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/NOVACProgram#58]
The new upload server at Chalmers will use SFTP protocol once implemented.  This change is required before we can switch to the new server.

**Comment by mattias42** [comment]
Implementation completed in branch 'sftp'. Should merge this with master branch for version 3.2. 
SFTP implementation uses libCurl for the communication and the program will require the file libcurl.dll to run (libcurl-d.dll in debug). This file is checked in the path /curl/win32/bin/
