### ISSUE TITLE
User-configurable spectrometer

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/NOVACProgram#6]
Make it possible to configure a 'custom' spectrometer using configurations files. This to make the program able to handle future types of spectrometers without having to rebuild.
Examples of parameters to save are number of pixels and saturation intensity.

**Comment by dnorgaard-usgs** [comment]
More details on parameters to save: # of bits, # of pixels, offset removal.

**Comment by mattias42** [comment]
Implemented in version 3.2 through commit  0ee10c2 . Was implementing this anyway in NovacPPP and made the same solution here.

**Comment by mattias42** [comment]
Also updated the SpectrometerModel with number of pixels, in commit baf9950.

**Comment by dnorgaard-usgs** [comment]
Looks like it works to me.
