### ISSUE TITLE
Allow FTP to instrument to use hostname

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/NOVACProgram#81]
Christoph is considering the use of cell modem for the installs he is planning at PNG in June.  It is unclear yet how it will work there, but the thought is it will unlikely have static IP address and may require a hostname to connect with.  It's possible it may be that we can't connect to the instrument this way (only instrument can connect out), but just in case, he would like the software to be able to support hostname.

**Comment by mattias42** [comment]
Problem probably resolved. Fixed this issue, but I don't have any scanner to test with so I cannot fully validate that the code does work. Pushed to new branch 'issue_#81_FTP_with_hostname' such that we can validate the fix there. 
@Diane, can you test and merge with master if ok?
