### ISSUE TITLE
Flux calculation appears broken in version 3.1 beta

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#88]
In testing the beta release of NOVAC Program v3.1 uploaded to the ftp server, it looks like the flux calculation is no longer working. Specifically, I clicked Analysis->Flux in the menu, then loaded an Evaluation Log that I had from Sabancaya. When I the click Calculate, I get some pretty ridiculous (much too high) numbers. Please have a look what has changed there since the last version. Version 3.0 of the program does not appear to have this issue. Thank you!

**Comment by christophkern** [comment]
Attaching an example EvaluationLog, as well as two screenshots showing the difference in flux results for scan 13 of 46 in this EvaluationLog in versions 3.0 and 3.1

[EvaluationLog_D2J2809_2018.04.27.txt](https://github.com/NOVACProject/NOVACProgram/files/3267812/EvaluationLog_D2J2809_2018.04.27.txt)

![ver3 0](https://user-images.githubusercontent.com/15023271/59136638-e1bdd880-8938-11e9-8476-80d900618b5a.jpg)

![ver3 1](https://user-images.githubusercontent.com/15023271/59136642-e4b8c900-8938-11e9-93b5-95f8e1f96be5.jpg)

**Comment by dnorgaard-usgs** [comment]
There is currently a lot of refactoring going on and functions from Common to calculate flux were moved to SpectralEvaluation project. It appears gas factor was not taken into account while calculating the average vertical column in the new functions.
