### ISSUE TITLE
Duplicate column density results / program crashes during Re Analysis

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#89]
I recently used NOVAC Program v3.0 to do a spectral re-analysis of Sabancaya data. I later realized that the fluxes I was getting (and reporting) were a factor of 2 too high. The reason for this was that the spectral ReEvaluation was writing duplicate entries into the ReEvaluationLog it was creating. Here's how to replicate the problem in v3.0:

Click Analysis - ReEvaluate
Select some example scans (provided below)
Click Fit window
Select an SO2 reference file (provided below)
Click Find Optimal Shift (turning it on)
Click Do Evaluation and Do Evaluation

After the evaluation runs through, open the ReEvaluationLog. You should find that in each scan, the scan angles run from -90 to 90, but then restart at -90 and run to 90 again.

The fatal thing about this is that if you open this ReEvaluationLog in the NOVACProgram using the Flux dialog, then calculate a flux, you actually get a factor of 2 higher flux than if you remove the duplicate entries in the scan. Pretty dangerous!

I tried to replicate the problem in v3.1 beta, but that version actually crashes completely when trying to ReEvaluate the same dataset. Seems to be another, different issue.

Example Scans (unzip before selecting in ReEvaluate tab:
[D2J2809_180427_1655_0.zip](https://github.com/NOVACProject/NOVACProgram/files/3267838/D2J2809_180427_1655_0.zip)

Use this SO2 reference file:
[D2J2809_0_SO2_20180421_0349.txt](https://github.com/NOVACProject/NOVACProgram/files/3267840/D2J2809_0_SO2_20180421_0349.txt)

**Comment by dnorgaard-usgs** [comment]
Read access violation in 3.1.  Call stack:

>	NovacProgram.exe!CBasicMath::Div(double * fFirst, double * fSec, int iSize, double fFactor) Line 787	C++
 	NovacProgram.exe!Evaluation::CEvaluationBase::PrepareSpectra_HP_Div(double * skyArray, double * measArray, const Evaluation::CFitWindow & window) Line 227	C++
 	NovacProgram.exe!Evaluation::CEvaluationBase::PrepareSpectra(double * sky, double * meas, const Evaluation::CFitWindow & window) Line 211	C++
 	NovacProgram.exe!Evaluation::CEvaluationBase::Evaluate(const CSpectrum & measured, int numSteps) Line 359	C++
 	NovacProgram.exe!Evaluation::CScanEvaluation::EvaluateScan(const ATL::CStringT<char,StrTraitMFC<char,ATL::ChTraitsCRT<char> > > & scanfile, const Evaluation::CFitWindow & window, bool * fRun, const Configuration::CDarkSettings * darkSettings) Line 278	C++
 	NovacProgram.exe!ReEvaluation::CReEvaluator::DoEvaluation() Line 172	C++
 	NovacProgram.exe!DoEvaluation(void * pParam) Line 14	C++
 	NovacProgram.exe!_AfxThreadEntry(void * pParam) Line 109	C++
 	NovacProgram.exe!invoke_thread_procedure(unsigned int(__stdcall*)(void *) procedure, void * const context) Line 92	C++
 	NovacProgram.exe!thread_start<unsigned int (__stdcall*)(void *)>(void * const parameter) Line 115	C++

Seems the skyArray being passed into EvaluationBase:PrepareSpectra_HP_Div (and PrepareSpectra above) is empty.

**Comment by dnorgaard-usgs** [comment]
Duplicate entries fixed by Mattias's last commit.
