### ISSUE TITLE
SO2 columns from the same scan initially plot at the same time in the history

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#99]
This issue was found while testing the Matupit DOAS system in Rabaul, Papua New Guinea. This system uses the 'fixed' angle mode to measure the SO2 column density of SO2 just downwind of Tavurvur volcano. The scan definition in the cfg.txt consists of only 3 lines: sky, dark and fixed (see attached file). 
When the data come into the NOVAC program at RVO, the software realizes that the instrument is running fixed angle mode (although it says 'received stratospheric measurement' in the log displayed at the bottom of the program, but this doesn't seem to mess things up) and it plots the SO2 column densities vs time. When going to the history plot, however, one finds that all points downloaded since the last program restart plot vertically binned by 'scan' or in this case rather by .pak file, since they aren't really scans. If you restart the program then these points spread out to cover the appropriate time range. Is there a way to plot them at the correct time right away? Attaching a screen shot where you can see new data coming in on the right...

[cfg.txt](https://github.com/NOVACProject/NOVACProgram/files/3366623/cfg.txt)

![before_prog_restart](https://user-images.githubusercontent.com/15023271/60782058-59756200-a188-11e9-9484-c9d29bbc02fc.jpg)

![after_prog_restart](https://user-images.githubusercontent.com/15023271/60782057-58dccb80-a188-11e9-9012-79abe56193dc.jpg)

**Comment by dnorgaard-usgs** [comment]
My config:

%-----pos----time-sum1-sum2--chn--basename----- repetitions--flag
MEAS=0 -1 15 1 0 sky 1 0
MEAS=100 0 15 1 0 dark 1 0
MEAS=-20 0 15 1 0 scan 25 0

As it is running: 

![image](https://user-images.githubusercontent.com/25251719/61316209-55af9400-a7b5-11e9-818d-5fe8e67a4b82.png)

After restart:

![image](https://user-images.githubusercontent.com/25251719/61316425-cfe01880-a7b5-11e9-8f8a-d0ba6fb04732.png)

Will update my cfg to match Matupit DOAS and see what happens.

**Comment by dnorgaard-usgs** [comment]
Now with:

%-----pos----time-sum1-sum2--chn--basename----- repetitions--flag
MEAS=32 -1 15 4 0 sky 1 0
MEAS=100 0 15 4 0 dark 1 0
MEAS=-2 0 15 4 0 fixed 25 0

![image](https://user-images.githubusercontent.com/25251719/61318904-f6548280-a7ba-11e9-9b07-f9ab53b4445f.png)

![image](https://user-images.githubusercontent.com/25251719/61319027-361b6a00-a7bb-11e9-95d6-03c3e7303329.png)

The difference is plot from scans coming in real-time vs scans from eval log (after restart).  Will look into why plots from scans in real-time isn't plotting as expected.

**Comment by dnorgaard-usgs** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/25251719/61324500-71239a80-a7c7-11e9-88d4-bd58347c8480.png)
